version: '3.4'

services:

  traderengine.mariadb:
    container_name: traderengine.mariadb
    image: mariadb:latest
    # command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./.volumes/db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       
  traderengine.api:
    container_name: traderengine.api
    image: ${DOCKER_REGISTRY-}traderengine.api
    restart: unless-stopped
    build:
      context: .
      dockerfile: TraderEngine.API/Dockerfile
      args:
        - TAG=6.0-alpine-arm64v8
    tty: true
    environment:
      - TZ=Europe/Amsterdam
      - ConnectionStrings__MySql=server=traderengine.mariadb;port=3306;database=${MYSQL_DATABASE};uid=${MYSQL_USERNAME};pwd=${MYSQL_PASSWORD};

  traderengine.cli:
    container_name: traderengine.cli
    image: ${DOCKER_REGISTRY-}traderengine.cli
    restart: unless-stopped
    build:
      context: .
      dockerfile: TraderEngine.CLI/Dockerfile
      args:
        - TAG=6.0-alpine-arm64v8
    depends_on:
      - traderengine.api
      - traderengine.mariadb
    tty: true
    environment:
      - TZ=Europe/Amsterdam
      - Addresses__TRADER_API=http://traderengine.api
      - CoinMarketCap__API_KEY=${CMC_API_KEY}
      - ConnectionStrings__MySql=server=traderengine.mariadb;port=3306;database=${MYSQL_DATABASE};uid=${MYSQL_USERNAME};pwd=${MYSQL_PASSWORD};
      - ConnectionStrings__WordPress=server=traderengine.mariadb;port=3306;database=${CMS_DATABASE};uid=${CMS_USERNAME};pwd=${CMS_PASSWORD};
