services:

  traderengine.postgres:
    container_name: traderengine.postgres
    image: timescale/timescaledb:2.28.3-pg18
    volumes:
      - ./.volumes/postgres-data:/var/lib/postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  traderengine.api:
    container_name: traderengine.api
    image: ${DOCKER_REGISTRY-}traderengine.api:${TAG:-latest}
    restart: unless-stopped
    build:
      context: .
      dockerfile: TraderEngine.API/Dockerfile
    depends_on:
      - traderengine.postgres
    tty: true
    volumes:
      - ./.volumes/secrets:/app/secrets
    environment:
      - TZ=Europe/Amsterdam
      - CoinMarketCap__API_KEY=${CMC_API_KEY}
      - ConnectionStrings__Postgres=Host=traderengine.postgres;Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}
      - DataProtection__KeyRingPath=/app/secrets
      - Jwt__SigningKey=${JWT_SIGNING_KEY}
      - AdminSeed__UserName=${ADMIN_USERNAME}
      - AdminSeed__Email=${ADMIN_EMAIL}
      - AdminSeed__Password=${ADMIN_PASSWORD}
      - EmailSettings__SmtpServer=${SMTP_SERVER}
      - EmailSettings__SmtpPort=${SMTP_PORT}
      - EmailSettings__SmtpUsername=${SMTP_USERNAME}
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD}
      - EmailSettings__FromAddress=${FROM_EMAIL_ADDRESS}
