version: '3.4'

services:
  
  traderengine.mariadb:
    ports:
      - "3306:3306"

  traderengine.api:
    build:
      args:
        - TAG=8.0-alpine
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  traderengine.cli:
    build:
      args:
        - TAG=8.0-alpine
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  traderengine.cryptography:
    image: bvandevliet/cryptography:linux-amd64
    ports:
      - "5010:80"
