version: '3.4'

services:
  
  traderengine.mariadb:
    ports:
      - "3306:3306"

  traderengine.api:
    build:
      args:
        - TAG=6.0-alpine
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4080:80"

  traderengine.cli:
    build:
      args:
        - TAG=6.0-alpine
        - MODE=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
