version: '3.4'

services:

  traderengine.mariadb:
    container_name: traderengine.mariadb
    image: mariadb:latest
    # command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./.volumes/db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      
  traderengine.api:
    container_name: traderengine.api
    image: ${DOCKER_REGISTRY-}traderengine.api:${TAG:-latest}
    restart: unless-stopped
    build:
      context: .
      dockerfile: TraderEngine.API/Dockerfile
    tty: true
    environment:
      - TZ=Europe/Amsterdam
      - ConnectionStrings__MySql=server=traderengine.mariadb;port=3306;database=${MYSQL_DATABASE};uid=${MYSQL_USERNAME};pwd=${MYSQL_PASSWORD};Pooling=true;MinPoolSize=0;MaxPoolSize=8;

  traderengine.cli:
    container_name: traderengine.cli
    image: ${DOCKER_REGISTRY-}traderengine.cli:${TAG:-latest}
    restart: unless-stopped
    build:
      context: .
      dockerfile: TraderEngine.CLI/Dockerfile
    depends_on:
      - traderengine.api
      - traderengine.mariadb
    tty: true
    environment:
      - TZ=Europe/Amsterdam
      - Addresses__TRADER_API=http://traderengine.api
      - Addresses__TRADER_CRYPTO=http://traderengine.cryptography
      - CoinMarketCap__API_KEY=${CMC_API_KEY}
      - ConnectionStrings__MySql=server=traderengine.mariadb;port=3306;database=${MYSQL_DATABASE};uid=${MYSQL_USERNAME};pwd=${MYSQL_PASSWORD};Pooling=true;MinPoolSize=0;MaxPoolSize=8;
      - ConnectionStrings__CMS=server=traderengine.mariadb;port=3306;database=${CMS_DATABASE};uid=${CMS_USERNAME};pwd=${CMS_PASSWORD};Pooling=true;MinPoolSize=0;MaxPoolSize=8;
      - CmsDbSettings__TablePrefix=${CMS_TABLE_PREFIX}
      - EmailSettings__SmtpServer=${SMTP_SERVER}
      - EmailSettings__SmtpPort=${SMTP_PORT}
      - EmailSettings__SmtpUsername=${SMTP_USERNAME}
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD}
      - EmailSettings__FromAddress=${FROM_EMAIL_ADDRESS}

  traderengine.cryptography:
    container_name: traderengine.cryptography
    image: bvandevliet/cryptography:${TAG:-latest}
    restart: unless-stopped
    tty: true
    volumes:
      - ./.volumes/secrets:/app/secrets
    environment:
      - TZ=Europe/Amsterdam
      - AllowedHosts=*
