import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import json from '@eslint/json';
import markdown from '@eslint/markdown';
import css from '@eslint/css';
import { defineConfig } from 'eslint/config';

export default defineConfig([
  { files: ['**/*.{js,mjs,cjs,ts,mts,cts}'], plugins: { js }, extends: ['js/recommended'], languageOptions: { globals: globals.browser } },
  tseslint.configs.recommended,
  { files: ['**/*.{js,mjs,cjs,ts,mts,cts}'],
    rules: {
      'arrow-body-style': 'error',
      'array-bracket-newline': ['error', 'consistent'],
      'array-bracket-spacing': 'error',
      'array-callback-return': 'warn',
      'array-element-newline': ['error', 'consistent'],
      'arrow-parens': ['error', 'as-needed'],
      'arrow-spacing': 'error',
      'block-scoped-var': 'warn',
      'block-spacing': 'error',
      'brace-style': ['error', 'allman', { allowSingleLine: true }],
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': 'error',
      'consistent-return': 'warn',
      curly: 'error',
      'default-case-last': 'error',
      'default-param-last': ['error'],
      'dot-location': ['error', 'property'],
      'dot-notation': 'error',
      'eol-last': ['error', 'never'],
      eqeqeq: ['error', 'smart'],
      'func-call-spacing': ['error'],
      'func-style': ['error', 'declaration'],
      'function-call-argument-newline': ['error', 'consistent'],
      'function-paren-newline': ['error', 'consistent'],
      'generator-star-spacing': 'error',
      indent: ['error', 2, { SwitchCase: 1 }],
      'key-spacing': 'error',
      'keyword-spacing': ['error'],
      'linebreak-style': ['error', 'unix'],
      'lines-between-class-members': ['error'],
      'new-parens': 'error',
      'no-dupe-class-members': ['error'],
      'no-duplicate-imports': 'error',
      'no-else-return': 'warn',
      'no-empty': 'error',
      'no-empty-function': ['error'],
      'no-eval': 'error',
      'no-eq-null': 'warn',
      'no-explicit-any': 'off',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-label': 'error',
      'no-extra-semi': ['error'],
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': ['error'],
      'no-lone-blocks': 'error',
      'no-lonely-if': 'warn',
      'no-loop-func': ['error'],
      'no-loss-of-precision': ['error'],
      'no-mixed-operators': 'warn',
      'no-multi-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'warn',
      'no-promise-executor-return': 'error',
      'no-prototype-builtins': 'warn',
      'no-redeclare': ['error'],
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-self-compare': 'error',
      'no-shadow': ['warn'],
      'no-tabs': 'error',
      'no-template-curly-in-string': 'warn',
      'no-throw-literal': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': 'error',
      'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
      'no-unused-private-class-members': 'error',
      'no-unused-vars': ['warn'],
      'no-use-before-define': ['error'],
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': ['error'],
      'no-useless-rename': 'error',
      'no-useless-return': 'warn',
      'no-var': 'warn',
      'no-void': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': ['error', 'always'],
      'operator-assignment': 'error',
      'operator-linebreak': ['error', 'before', { overrides: { '=': 'ignore' } }],
      'padded-blocks': ['error', 'never', { allowSingleLineBlocks: true }],
      'padding-line-between-statements': ['error',
        {
          blankLine: 'always',
          prev: 'directive',
          next: '*',
        },
        {
          blankLine: 'never',
          prev: 'directive',
          next: 'directive',
        },
        {
          blankLine: 'always',
          prev: 'import',
          next: '*',
        },
        {
          blankLine: 'never',
          prev: 'import',
          next: 'import',
        },
        {
          blankLine: 'always',
          prev: '*',
          next: ['block', 'block-like'],
        },
        {
          blankLine: 'always',
          prev: ['block', 'block-like'],
          next: '*',
        },
        {
          blankLine: 'always',
          prev: ['case', 'default'],
          next: '*',
        }],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'warn',
      'prefer-destructuring': 'warn',
      'prefer-exponentiation-operator': 'error',
      'prefer-numeric-literals': 'warn',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'warn',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'warn',
      'prefer-template': 'error',
      'quote-props': ['error', 'as-needed'],
      quotes: ['error', 'single'],
      radix: ['error', 'as-needed'],
      'require-await': 'error',
      'require-unicode-regexp': 'error',
      'rest-spread-spacing': ['error', 'never'],
      semi: ['error'],
      'semi-spacing': 'error',
      'semi-style': 'error',
      'space-before-blocks': ['error'],
      'space-before-function-paren': ['error'],
      'space-in-parens': 'error',
      'space-infix-ops': ['error'],
      'space-unary-ops': 'error',
      'spaced-comment': 'error',
      strict: 'error',
      'switch-colon-spacing': 'error',
      'template-curly-spacing': 'error',
      'template-tag-spacing': ['error', 'always'],
      'wrap-iife': 'error',
      'yield-star-spacing': 'error',
      yoda: ['error', 'never', { onlyEquality: true }],
    } },
  { files: ['**/*.json'], plugins: { json }, language: 'json/json', extends: ['json/recommended'] },
  { files: ['**/*.jsonc'], plugins: { json }, language: 'json/jsonc', extends: ['json/recommended'] },
  { files: ['**/*.json5'], plugins: { json }, language: 'json/json5', extends: ['json/recommended'] },
  { files: ['**/*.md'], plugins: { markdown }, language: 'markdown/gfm', extends: ['markdown/recommended'] },
  { files: ['**/*.css'], plugins: { css }, language: 'css/css', extends: ['css/recommended'] },
]);