# Note: This workflow only updates the cache. You should create a separate workflow for your actual Trivy scans.
# In your scan workflow, set TRIVY_SKIP_DB_UPDATE=true and TRIVY_SKIP_JAVA_DB_UPDATE=true.
name: Update Trivy Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  update-trivy-db:
    name: Update Trivy cache
    uses: bvandevliet/Actions.Shared/.github/workflows/update-trivy-cache.yml@master